1. 活性化関数であるSigmoid関数とSoftmax関数をpythonで実装して下さい．
    1. Sigmoid関数は次の課題でそのまま使用するので、Numpyを入力としてください

In [1]:
# import 
import numpy as np

In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))


2. 3層マルチパーセプトロンによるNNの実装を行い、出力が正しいか確認してください．
    1. 下記のサンプルコードにおけるforward部分を実装してみてください. 活性化関数にはSigmoid関数を使用してください

In [13]:
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network

def forward(network, x):
    # layer 1
    W1=network['W1']
    b1=network['b1']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2 layer3を実装してみてください   
    # layer 2
    W2=network['W2']
    b2=network['b2']
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    # layer 3
    W3=network['W3']
    b3=network['b3']
    a3=np.dot(z2,W3)+b3
    y = a3
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

[[0.31682708 0.69627909]]


1. バッチ処理の行い方についてサンプルコードを実行し、扱い方のイメージを掴んでください．
    1. 複数の入力を逐次的に処理します

In [16]:
import numpy as np
import random  
network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(y_batch) # 確認用

[[0.31368531 0.68929553]
 [0.31005982 0.68124676]
 [0.3119354  0.68540146]
 [0.310414   0.68203373]
 [0.31286164 0.6874665 ]
 [0.31360048 0.68911406]
 [0.3130491  0.68787481]
 [0.31578905 0.69396418]
 [0.31600549 0.69444779]
 [0.31284757 0.68743412]
 [0.31770381 0.69822613]
 [0.31491849 0.69201958]
 [0.31544803 0.69320866]
 [0.31405173 0.69010413]
 [0.31410905 0.69023031]
 [0.31177063 0.68503916]]
[[0.31728398 0.6972851 ]
 [0.31143311 0.68429375]
 [0.31450946 0.69112716]
 [0.3129118  0.68757534]
 [0.31189868 0.68533273]
 [0.31094911 0.68321572]
 [0.3125426  0.68675804]
 [0.31529436 0.69286102]
 [0.31727691 0.69727421]
 [0.31435481 0.69076649]
 [0.3180851  0.699071  ]
 [0.31496706 0.69213432]
 [0.31682558 0.6962648 ]
 [0.31757487 0.69793418]
 [0.30980643 0.68068806]
 [0.31029078 0.68175819]]
[[0.31163934 0.68475591]
 [0.31642077 0.69536554]
 [0.31100672 0.68335256]
 [0.31610937 0.69467651]
 [0.31657918 0.69572374]
 [0.31738241 0.69750313]
 [0.31673524 0.69606761]
 [0.31244837 0.68653828

### 感想

よくわからないものとして捉えていたニューラルネットワークが、思っていたよりも単純な構成であったのでびっくりした。
もしかしたら、ネットワークの構成よりもデータの整形の方が大変なのかもしれないと思った。

### 参考文献
[1] 斎藤康毅, 3.ニューラルネットワーク, ゼロから作るDeepLearning，2020年, オライリージャパン，pp.39-71